version: "3"
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rafaballerini
      - MONGO_INITDB_ROOT_PASSWORD=PosTech1404
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
